// <auto-generated />
using System;
using AirBB.Models.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirBB.Migrations
{
    [DbContext(typeof(AirBBContext))]
    partial class AirBBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AirBB.Models.DomainModels.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("AppUserId");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            AppUserId = 1,
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@airbb.com",
                            Name = "Admin User",
                            Password = "adminpass",
                            PhoneNumber = "1234567890",
                            SSN = "111-11-1111",
                            UserType = "Admin"
                        },
                        new
                        {
                            AppUserId = 2,
                            DOB = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "client@airbb.com",
                            Name = "Client User",
                            Password = "clientpass",
                            PhoneNumber = "9876543210",
                            SSN = "222-22-2222",
                            UserType = "Client"
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "Chicago",
                            Region = "Illinois"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "New York",
                            Region = "New York"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "Miami",
                            Region = "Florida"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Atlanta",
                            Region = "Georgia"
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accommodation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bathrooms")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuiltYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ResidencePicture")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 1,
                            Accommodation = "Full Apartment",
                            Bathrooms = 2m,
                            Bedrooms = 2,
                            BuiltYear = 2000,
                            GuestNumber = 4,
                            LocationId = 1,
                            Name = "Chicago Loop Apartment",
                            OwnerId = 1,
                            PricePerNight = 180m,
                            ResidencePicture = "chi1.jpg"
                        },
                        new
                        {
                            ResidenceId = 2,
                            Accommodation = "Condo Suite",
                            Bathrooms = 1m,
                            Bedrooms = 1,
                            BuiltYear = 2005,
                            GuestNumber = 2,
                            LocationId = 1,
                            Name = "River North Condo",
                            OwnerId = 1,
                            PricePerNight = 140m,
                            ResidencePicture = "chi2.jpg"
                        },
                        new
                        {
                            ResidenceId = 3,
                            Accommodation = "Loft",
                            Bathrooms = 1m,
                            Bedrooms = 1,
                            BuiltYear = 2010,
                            GuestNumber = 3,
                            LocationId = 2,
                            Name = "Midtown Loft",
                            OwnerId = 2,
                            PricePerNight = 220m,
                            ResidencePicture = "ny1.jpg"
                        },
                        new
                        {
                            ResidenceId = 4,
                            Accommodation = "Brownstone Home",
                            Bathrooms = 1m,
                            Bedrooms = 2,
                            BuiltYear = 1995,
                            GuestNumber = 4,
                            LocationId = 2,
                            Name = "Brooklyn Brownstone",
                            OwnerId = 2,
                            PricePerNight = 200m,
                            ResidencePicture = "ny2.jpg"
                        },
                        new
                        {
                            ResidenceId = 5,
                            Accommodation = "Beach House",
                            Bathrooms = 2m,
                            Bedrooms = 3,
                            BuiltYear = 2012,
                            GuestNumber = 6,
                            LocationId = 3,
                            Name = "Miami Beach House",
                            OwnerId = 3,
                            PricePerNight = 260m,
                            ResidencePicture = "miami1.jpg"
                        },
                        new
                        {
                            ResidenceId = 6,
                            Accommodation = "Condo",
                            Bathrooms = 1m,
                            Bedrooms = 1,
                            BuiltYear = 2015,
                            GuestNumber = 2,
                            LocationId = 3,
                            Name = "South Beach Condo",
                            OwnerId = 3,
                            PricePerNight = 180m,
                            ResidencePicture = "miami2.jpg"
                        },
                        new
                        {
                            ResidenceId = 7,
                            Accommodation = "Family House",
                            Bathrooms = 2m,
                            Bedrooms = 3,
                            BuiltYear = 2003,
                            GuestNumber = 5,
                            LocationId = 4,
                            Name = "Suburban Family Home",
                            OwnerId = 4,
                            PricePerNight = 190m,
                            ResidencePicture = "atlanta1.jpg"
                        },
                        new
                        {
                            ResidenceId = 8,
                            Accommodation = "Apartment",
                            Bathrooms = 1m,
                            Bedrooms = 2,
                            BuiltYear = 2008,
                            GuestNumber = 3,
                            LocationId = 4,
                            Name = "Downtown Apartment",
                            OwnerId = 4,
                            PricePerNight = 160m,
                            ResidencePicture = "atlanta2.jpg"
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Reservation", b =>
                {
                    b.HasOne("AirBB.Models.DomainModels.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Residence", b =>
                {
                    b.HasOne("AirBB.Models.DomainModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
